# Generated by Django 4.0 on 2021-12-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
        migrations.AddField(
            model_name='contact',
            name='cname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_no',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='purpose',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
