# Generated by Django 4.0 on 2021-12-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_remove_contact_comment_remove_contact_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, null=True)),
                ('contact_no', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('feedback', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_no',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='purpose',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='cname',
            new_name='full_name',
        ),
    ]
