# Generated by Django 4.0 on 2021-12-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_feedback_rename_contact_no_contact_comment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_us',
        ),
    ]
